# Base configuration for Sustainable Credit Risk AI System

environment: development
debug: true
log_level: INFO

# Paths
data_path: "data/"
logs_path: "logs/"
models_path: "models/"
keys_path: "keys/"

# Database configuration
database:
  host: "localhost"
  port: 5432
  database: "credit_risk_ai"
  username: "postgres"
  password: ""
  ssl_mode: "prefer"

# Model configuration
model:
  batch_size: 32
  learning_rate: 0.001
  epochs: 100
  early_stopping_patience: 10
  model_save_path: "models/"
  checkpoint_interval: 10

# Security configuration
security:
  encryption_key_path: "keys/encryption.key"
  jwt_secret_key: ""
  jwt_expiration_hours: 24
  api_key_length: 32
  differential_privacy_epsilon: 1.0
  enable_audit_logging: true

# Federated learning configuration
federated:
  server_host: "localhost"
  server_port: 8080
  num_rounds: 10
  min_clients: 2
  client_fraction: 1.0
  secure_aggregation: true

# Sustainability configuration
sustainability:
  enable_energy_tracking: true
  carbon_region: "US"
  energy_threshold_kwh: 10.0
  carbon_budget_kg: 100.0
  report_interval_hours: 24

# API configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout_seconds: 30
  max_request_size_mb: 100
  rate_limit_per_minute: 1000