# Production environment configuration

environment: production
debug: false
log_level: INFO

# Production security settings
security:
  jwt_expiration_hours: 8  # Shorter sessions in production
  differential_privacy_epsilon: 0.5  # Stricter privacy in production
  enable_audit_logging: true

# Production API settings
api:
  host: "0.0.0.0"
  port: 8000
  workers: 8
  timeout_seconds: 15
  rate_limit_per_minute: 100  # Strict rate limiting

# Production sustainability settings
sustainability:
  carbon_budget_kg: 50.0  # Stricter carbon budget
  energy_threshold_kwh: 5.0  # Lower energy threshold