"""Neural Architecture Search (NAS) package for automated architecture discovery."""

from .neural_architecture_search import (
    NeuralArchitectureSearch,
    ArchitectureSpec,
    SearchSpace,
    NASConfig,
    NASResult,
    ArchitectureGenerator,
    RandomArchitectureGenerator,
    ArchitectureEvaluator,
    run_nas_search,
    get_default_nas_config,
    get_fast_nas_config,
    get_comprehensive_nas_config,
    get_sustainable_search_space,
    create_architecture_from_config,
    export_architecture_to_config,
    save_nas_results,
    load_nas_results,
)

__all__ = [
    "NeuralArchitectureSearch",
    "ArchitectureSpec",
    "SearchSpace",
    "NASConfig",
    "NASResult",
    "ArchitectureGenerator",
    "RandomArchitectureGenerator",
    "ArchitectureEvaluator",
    "run_nas_search",
    "get_default_nas_config",
    "get_fast_nas_config",
    "get_comprehensive_nas_config",
    "get_sustainable_search_space",
    "create_architecture_from_config",
    "export_architecture_to_config",
    "save_nas_results",
    "load_nas_results",
]
