name: Security Scan with Trivy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

# Required for uploading SARIF to Code Scanning
permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Free up disk space
      run: |
        # Remove unnecessary packages and files to free up space
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker system prune -af
        df -h

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        # Ensure data file exists or create sample
        if [ ! -f "Bank_data.csv" ]; then
          echo "Creating sample data file..."
          echo "customer_id,age,gender,marital_status,employment_type,annual_income_inr,loan_amount_inr,loan_purpose,loan_term_months,credit_score,num_open_credit_accounts,num_delinquent_accounts,debt_to_income_ratio,past_default,default" > Bank_data.csv
          echo "SAMPLE001,35,Male,Married,Salaried,500000,100000,Personal Loan,24,750,3,0,0.3,0,0" >> Bank_data.csv
        fi
        docker build -t sustainable-credit-risk-ai:test --target production -f infrastructure/docker/Dockerfile .

    - name: Run Trivy filesystem scanner (lightweight)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-fs-results.sarif'
        scanners: 'vuln,secret,misconfig'
        severity: 'CRITICAL,HIGH,MEDIUM'
        skip-version-check: true
        ignore-unfixed: true

    - name: Run Trivy image scanner with optimizations
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'sustainable-credit-risk-ai:test'
        format: 'table'
        output: 'trivy-image-results.txt'
        scanners: 'vuln'
        severity: 'CRITICAL,HIGH'
        skip-version-check: true
        ignore-unfixed: true
        # Use tar format to reduce memory usage
        input: 'sustainable-credit-risk-ai:test'
        # Limit concurrent scans
        parallel: 1
        # Use lighter database
        light: true

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always() && (github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork)
      with:
        sarif_file: 'trivy-fs-results.sarif'

    - name: Display image scan results
      if: always()
      run: |
        echo "=== Image Vulnerability Scan Results ==="
        cat trivy-image-results.txt || echo "No image scan results found"

    - name: Clean up Docker images to free space
      if: always()
      run: |
        docker system prune -af
        docker volume prune -f
